@startuml

title __APP's Class Diagram__\n

  namespace androidx.databinding {
    class androidx.databinding.DataBinderMapperImpl {
    }
  }
  

  namespace androidx.databinding {
    interface androidx.databinding.DataBindingComponent {
    }
  }
  

  namespace androidx.databinding {
    namespace library.baseAdapters {
      class androidx.databinding.library.baseAdapters.BR {
      }
    }
  }
  

  namespace com.kasuncreations.echarity {
    class com.kasuncreations.echarity.BR {
    }
  }
  

  namespace com.kasuncreations.echarity {
    class com.kasuncreations.echarity.BuildConfig {
    }
  }
  

  namespace com.kasuncreations.echarity {
    class com.kasuncreations.echarity.DataBinderMapperImpl {
    }
  }
  

  namespace com.kasuncreations.echarity {
    namespace databinding {
      class com.kasuncreations.echarity.databinding.ActivityLoginBindingImpl {
      }
    }
  }
  

  namespace com.kasuncreations.echarity {
    namespace databinding {
      class com.kasuncreations.echarity.databinding.ActivitySignUpBindingImpl {
      }
    }
  }
  

  namespace com.kasuncreations.echarity {
    namespace databinding {
      class com.kasuncreations.echarity.databinding.FragmentProfileBindingImpl {
      }
    }
  }
  

  namespace com.kasuncreations.echarity {
    namespace generated.callback {
      class com.kasuncreations.echarity.generated.callback.OnClickListener {
      }
    }
  }
  

  namespace com.kasuncreations.echarity {
    namespace presentation.auth {
      class com.kasuncreations.echarity.presentation.auth.LoginActivity_ViewBinding {
      }
    }
  }
  

  namespace com.kasuncreations.echarity {
    namespace presentation.chat {
      class com.kasuncreations.echarity.presentation.chat.ChatViewActivity_ViewBinding {
      }
    }
  }
  

  namespace com.kasuncreations.echarity {
    namespace presentation.main {
      class com.kasuncreations.echarity.presentation.main.MainActivity_ViewBinding {
      }
    }
  }
  

  namespace com.kasuncreations.echarity {
    namespace presentation.post {
      class com.kasuncreations.echarity.presentation.post.AddPostActivity_ViewBinding {
      }
    }
  }
  

  androidx.databinding.DataBinderMapperImpl -up-|> androidx.databinding.MergedDataBinderMapper
  com.kasuncreations.echarity.DataBinderMapperImpl -up-|> androidx.databinding.DataBinderMapper
  com.kasuncreations.echarity.databinding.ActivityLoginBindingImpl .up.|> com.kasuncreations.echarity.generated.callback.OnClickListener.Listener
  com.kasuncreations.echarity.databinding.ActivityLoginBindingImpl -up-|> com.kasuncreations.echarity.databinding.ActivityLoginBinding
  com.kasuncreations.echarity.databinding.ActivitySignUpBindingImpl .up.|> com.kasuncreations.echarity.generated.callback.OnClickListener.Listener
  com.kasuncreations.echarity.databinding.ActivitySignUpBindingImpl -up-|> com.kasuncreations.echarity.databinding.ActivitySignUpBinding
  com.kasuncreations.echarity.databinding.FragmentProfileBindingImpl -up-|> com.kasuncreations.echarity.databinding.FragmentProfileBinding
  com.kasuncreations.echarity.generated.callback.OnClickListener .up.|> android.view.View.OnClickListener
  com.kasuncreations.echarity.generated.callback.OnClickListener o-- com.kasuncreations.echarity.generated.callback.OnClickListener.Listener : mListener
  com.kasuncreations.echarity.presentation.auth.LoginActivity_ViewBinding .up.|> butterknife.Unbinder
  com.kasuncreations.echarity.presentation.auth.LoginActivity_ViewBinding o-- com.kasuncreations.echarity.presentation.auth.LoginActivity : target
  com.kasuncreations.echarity.presentation.chat.ChatViewActivity_ViewBinding .up.|> butterknife.Unbinder
  com.kasuncreations.echarity.presentation.chat.ChatViewActivity_ViewBinding o-- com.kasuncreations.echarity.presentation.chat.ChatViewActivity : target
  com.kasuncreations.echarity.presentation.main.MainActivity_ViewBinding .up.|> butterknife.Unbinder
  com.kasuncreations.echarity.presentation.main.MainActivity_ViewBinding o-- com.kasuncreations.echarity.presentation.main.MainActivity : target
  com.kasuncreations.echarity.presentation.post.AddPostActivity_ViewBinding .up.|> butterknife.Unbinder
  com.kasuncreations.echarity.presentation.post.AddPostActivity_ViewBinding o-- com.kasuncreations.echarity.presentation.post.AddPostActivity : target


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
